"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Product = { id: string; name: string; sku: string; variants: { id: string }[]; prices: { salePrice: string }[] };
type Method = { id: string; name: string; status: string };
type Customer = { id: string; name: string; status: string };
type SaleLine = { productId: string; quantity: string; price: string };

export function QuickSaleForm({ products, methods, customers }: { products: Product[]; methods: Method[]; customers: Customer[] }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [pending, setPending] = useState(false); const [error, setError] = useState<string>();
  const [lines, setLines] = useState<SaleLine[]>([{ productId: "", quantity: "1", price: "" }]);
  const estimatedTotal = useMemo(() => lines.reduce((total, line) => total + Number(line.quantity || 0) * Number(line.price || 0), 0), [lines]);
  function updateLine(index: number, field: keyof SaleLine, value: string) { setLines(current => current.map((line, currentIndex) => currentIndex === index ? { ...line, [field]: value } : line)); }
  function chooseProduct(index: number, productId: string) { const product = products.find(item => item.id === productId); updateLine(index, "productId", productId); if (product?.prices[0]) updateLine(index, "price", product.prices[0].salePrice); }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setError(undefined); const values = new FormData(event.currentTarget);
    const items = lines.map(line => { const product = products.find(item => item.id === line.productId); return product?.variants[0] ? { productVariantId: product.variants[0].id, quantity: Number(line.quantity), unitPrice: Number(line.price), discount: 0 } : null; });
    const method = methods.find(item => item.id === values.get("method"));
    if (items.some(item => !item) || !method) { setError("Complete os produtos e a forma de pagamento."); setPending(false); return; }
    try { const created = await fetch("/api/sales", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customerId: values.get("customer") || undefined, channel: values.get("channel"), items }) }); const sale = await created.json() as { id?: string; total?: string; message?: string }; if (!created.ok || !sale.id || !sale.total) throw new Error(sale.message ?? "Não foi possível criar a venda."); const confirmed = await fetch(`/api/sales/${sale.id}/confirm`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ payments: [{ paymentMethodId: method.id, amount: Number(sale.total) }] }) }); const confirmation = await confirmed.json() as { message?: string }; if (!confirmed.ok) throw new Error(confirmation.message ?? "Não foi possível confirmar a venda."); setOpen(false); setLines([{ productId: "", quantity: "1", price: "" }]); router.refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível registrar a venda."); } finally { setPending(false); }
  }
  if (!methods.some(method => method.status === "active")) return <p className="form-error">Configure uma forma de pagamento vinculada a uma conta financeira antes de registrar uma venda.</p>;
  if (!open) return <button className="button button-primary compact-button" onClick={() => setOpen(true)}>Nova venda</button>;
  return <section className="form-card"><div className="form-card-heading"><div><h2>Nova venda</h2><p>Ao confirmar, o estoque é baixado e o pagamento é registrado.</p></div><button className="close-button" onClick={() => setOpen(false)} aria-label="Fechar venda">×</button></div><form onSubmit={submit}><div className="form-grid"><div className="field"><label>Cliente <small>(opcional)</small><select name="customer"><option value="">Consumidor final</option>{customers.filter(customer => customer.status === "active").map(customer => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></label></div><div className="field"><label>Pagamento<select name="method" required>{methods.filter(method => method.status === "active").map(method => <option key={method.id} value={method.id}>{method.name}</option>)}</select></label></div><div className="field"><label>Canal<select name="channel" defaultValue="presencial"><option value="presencial">Presencial</option><option value="whatsapp">WhatsApp</option><option value="instagram">Instagram</option></select></label></div></div><fieldset className="sale-lines"><legend>Itens da venda</legend>{lines.map((line, index) => <div className="sale-line" key={index}><div className="field"><label>Produto<select value={line.productId} onChange={event => chooseProduct(index, event.target.value)} required><option value="">Selecione</option>{products.map(product => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select></label></div><div className="field"><label>Quantidade<input value={line.quantity} onChange={event => updateLine(index, "quantity", event.target.value)} type="number" min="0.001" step="0.001" required /></label></div><div className="field"><label>Preço unitário (R$)<input value={line.price} onChange={event => updateLine(index, "price", event.target.value)} type="number" min="0" step="0.01" required /></label></div>{lines.length > 1 && <button type="button" className="line-remove" onClick={() => setLines(current => current.filter((_, currentIndex) => currentIndex !== index))} aria-label="Remover item">Remover</button>}</div>)}</fieldset><div className="sale-footer"><button type="button" className="text-link button-link" onClick={() => setLines(current => [...current, { productId: "", quantity: "1", price: "" }])}>+ Adicionar item</button><strong>Total estimado: {new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(estimatedTotal)}</strong></div>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-primary compact-button" disabled={pending}>{pending ? "Confirmando…" : "Confirmar venda"}</button></form></section>;
}
