import { QuickSaleForm } from "@/components/sales/quick-sale-form";
import { backendAuthenticatedRequest, getSession } from "@/lib/session";
type Product = { id: string; name: string; sku: string; variants: { id: string }[]; prices: { salePrice: string }[] };
type Method = { id: string; name: string; status: string };
type Sale = { id: string; status: string; total: string; createdAt: string; items: unknown[] };
type Customer = { id: string; name: string; status: string };
const money = (v: string) => new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format(Number(v));
const saleStatus: Record<string, string> = { draft: "Rascunho", confirmed: "Confirmada", cancelled: "Cancelada", partially_returned: "Devolvida parcialmente", returned: "Devolvida" };
export default async function SalesPage() { const [sales, products, methods, customers, session] = await Promise.all([backendAuthenticatedRequest("/sales") as Promise<Sale[]>, backendAuthenticatedRequest("/catalog/products") as Promise<Product[]>, backendAuthenticatedRequest("/payments/methods") as Promise<Method[]>, backendAuthenticatedRequest("/customers") as Promise<Customer[]>, getSession() as Promise<{ permissions: string[] } | null>]); const canManage = session?.permissions.includes("manage_sales") ?? false; return <main className="page-content"><div className="page-heading"><div><h1>Vendas</h1><p>Uma venda atualiza estoque, CMV e pagamento em uma única operação.</p></div>{canManage && products.length > 0 && <QuickSaleForm products={products} methods={methods} customers={customers} />}</div>{products.length === 0 ? <section className="empty-card"><h2>Cadastre um produto antes de fazer uma venda</h2><p>Assim o sistema consegue validar a disponibilidade e preservar o custo histórico.</p></section> : sales.length === 0 ? <section className="empty-card"><h2>Você ainda não registrou nenhuma venda</h2><p>Comece uma venda para baixar o estoque e acompanhar seus resultados.</p></section> : <section className="data-card"><div className="table-wrap"><table><thead><tr><th>Venda</th><th>Status</th><th className="number">Itens</th><th className="number">Total</th></tr></thead><tbody>{sales.map((sale) => <tr key={sale.id}><td data-label="Venda"><strong>Venda #{sale.id.slice(0, 8)}</strong></td><td data-label="Status"><span className={`status-badge ${sale.status}`}>{saleStatus[sale.status] ?? sale.status}</span></td><td className="number" data-label="Itens">{sale.items.length}</td><td className="number" data-label="Total">{money(sale.total)}</td></tr>)}</tbody></table></div></section>}</main>; }
