"use client";

import { useState } from "react";
import { SelectField } from "@/components/ui/select-field";

type Company = { name: string; document: string | null; segment: string | null; email: string | null; phone: string | null; currency: string; timezone: string; operationStartDate: string | null; brandAccentColor: string; allowNegativeStock: boolean; allocationMethod: string; defaultMinStock: string | null; discountLimit: string | null };

export function CompanySettings({ company, canManage }: { company: Company; canManage: boolean }) {
  const [saved, setSaved] = useState(false); const [error, setError] = useState<string>(); const [pending, setPending] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setError(undefined); setSaved(false);
    const data = new FormData(event.currentTarget);
    const body = { name: data.get("name"), document: data.get("document"), segment: data.get("segment"), email: data.get("email"), phone: data.get("phone"), currency: data.get("currency"), timezone: data.get("timezone"), operationStartDate: data.get("operationStartDate"), brandAccentColor: data.get("brandAccentColor"), allowNegativeStock: data.get("allowNegativeStock") === "on", allocationMethod: data.get("allocationMethod"), defaultMinStock: data.get("defaultMinStock"), discountLimit: data.get("discountLimit") };
    try { const response = await fetch("/api/settings/company", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { message?: string }; if (!response.ok) throw new Error(payload.message ?? "Não foi possível salvar."); setSaved(true); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar."); }
    finally { setPending(false); }
  }
  return <form className="settings-company-form" onSubmit={submit}>
    <section className="wizard-form-section"><h3>Identificação da empresa</h3><div className="form-grid"><div className="field"><label htmlFor="company-name">Nome fantasia</label><input id="company-name" name="name" defaultValue={company.name} required disabled={!canManage} /></div><div className="field"><label htmlFor="company-document">CPF ou CNPJ</label><input id="company-document" name="document" defaultValue={company.document ?? ""} disabled={!canManage} /></div><div className="field"><label htmlFor="company-segment">Segmento</label><input id="company-segment" name="segment" defaultValue={company.segment ?? ""} disabled={!canManage} /></div><div className="field"><label htmlFor="company-start">Início da operação</label><input id="company-start" name="operationStartDate" type="date" defaultValue={company.operationStartDate?.slice(0, 10) ?? ""} disabled={!canManage} /></div></div></section>
    <section className="wizard-form-section"><h3>Contato e localização</h3><div className="form-grid"><div className="field"><label htmlFor="company-email">E-mail</label><input id="company-email" name="email" type="email" defaultValue={company.email ?? ""} disabled={!canManage} /></div><div className="field"><label htmlFor="company-phone">Telefone</label><input id="company-phone" name="phone" defaultValue={company.phone ?? ""} disabled={!canManage} /></div><SelectField label="Fuso horário" name="timezone" defaultValue={company.timezone} disabled={!canManage}><option value="America/Sao_Paulo">Brasília — São Paulo</option><option value="America/Manaus">Manaus</option><option value="America/Rio_Branco">Rio Branco</option><option value="America/Fortaleza">Fortaleza</option></SelectField><SelectField label="Moeda principal" name="currency" defaultValue={company.currency} disabled={!canManage}><option value="BRL">Real brasileiro (BRL)</option><option value="USD">Dólar americano (USD)</option><option value="EUR">Euro (EUR)</option></SelectField></div></section>
    <section className="wizard-form-section"><h3>Políticas operacionais</h3><div className="form-grid"><div className="field"><label htmlFor="company-color">Cor de destaque</label><input id="company-color" name="brandAccentColor" type="color" defaultValue={company.brandAccentColor} disabled={!canManage} /></div><SelectField label="Rateio padrão de compras" name="allocationMethod" defaultValue={company.allocationMethod} disabled={!canManage}><option value="proportional_value">Proporcional ao valor</option><option value="proportional_quantity">Proporcional à quantidade</option></SelectField><div className="field"><label htmlFor="default-stock">Estoque mínimo padrão</label><input id="default-stock" name="defaultMinStock" inputMode="decimal" defaultValue={company.defaultMinStock ?? ""} disabled={!canManage} /></div><div className="field"><label htmlFor="discount-limit">Limite de desconto (%)</label><input id="discount-limit" name="discountLimit" inputMode="decimal" defaultValue={company.discountLimit ?? ""} disabled={!canManage} /></div></div><label className="settings-check"><input type="checkbox" name="allowNegativeStock" defaultChecked={company.allowNegativeStock} disabled={!canManage} /><span><strong>Permitir estoque negativo</strong><small>Use apenas quando a operação exigir venda sem saldo disponível.</small></span></label></section>
    {error && <p className="form-error" role="alert">{error}</p>}{saved && <p className="form-success" role="status">Configurações salvas. Alterações operacionais valem para os próximos registros.</p>}
    {canManage && <div className="wizard-actions"><button className="button button-primary compact-button" disabled={pending}>{pending ? "Salvando…" : "Salvar configurações"}</button></div>}
  </form>;
}
